### ISSUE TITLE
make watch returning funky error

### ISSUE THREAD

**Issue by duckbox** [rehabstudio/fe-skeleton#29]
Seems to be something with es6 promise in the styles command

Ruby sass version ( Sass 3.4.6 (Selective Steve) )
```
➜  static git:(develop) make watch
gulp;
 - Loading module styles
 - Loading module scripts
 - Loading module build
 - Loading module default
[14:51:19] Using gulpfile ~/sites/planner-2.0/app/apps/triage/static/gulpfile.js
[14:51:19] Starting 'default'...
[14:51:19] Starting 'styles'...
[14:51:19] Starting 'scripts'...
[14:51:19] Finished 'default' after 7.44 ms
[14:51:19] 'styles' errored after 8.05 ms
[14:51:19] Error: Something went wrong.
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:161:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:187:15)
    at Gulp.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/chris/sites/planner-2.0/app/apps/triage/static/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/chris/sites/planner-2.0/app/apps/triage/static/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/chris/sites/planner-2.0/app/apps/triage/static/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/chris/sites/planner-2.0/app/apps/triage/static/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at /Users/chris/sites/planner-2.0/app/apps/triage/static/run/tasks/styles/gulp.js:38:13
    at $$$internal$$tryCatch (/Users/chris/sites/planner-2.0/app/apps/triage/static/node_modules/es6-promise/dist/es6-promise.js:304:16)
    at $$$internal$$invokeCallback (/Users/chris/sites/planner-2.0/app/apps/triage/static/node_modules/es6-promise/dist/es6-promise.js:316:17)
[14:51:19] Finished 'scripts' after 11 ms
```

**Comment by antwan1986** [comment]
Hey @duckbox,

Try testing this again. As of this morning, the master branch has had the `node-sass` branch merged into it. Also, there's a "test" branch with some dummy CSS and JS source files in it to test the compilation tasks. It's called `example/browserify` and if you check it out, you should definitely be able to run `gulp styles` without any problems occuring. Check `dist/css/main.css` to ensure output was correct.

Let me know how things work out!
Anthony

**Comment by antwan1986** [comment]
Closing due to lack of activity on the ticket.
